version: "3.3"

networks:
  SymfonyStore:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/project
      - ./logs:/var/log/nginx
      - ./config/ssls:/etc/nginx/ssls
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - SymfonyStore

  # php
  php-service:
    build: 
      context: .
      dockerfile: ./config/php/Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - SymfonyStore

  # mysql
  mysql-service:
    image: mysql:8.3.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PSWD}'
      MYSQL_USER: '${DB_USER_NAME}'
      MYSQL_PASSWORD: '${DB_USER_PSWD}'
    networks:
      - SymfonyStore

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql-service
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-service
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PSWD}'
    networks:
      - SymfonyStore

  # node
  node-service:
    build:
      context: .
      dockerfile: ./config/node/Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: node-container
    volumes:
      - ./app:/code
    networks:
      - SymfonyStore

  # mailpit (For testing email sending/receiving)
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - SymfonyStore